fix: enable development mode for the client
aerogear/graphback pull request #1957
Opened 2020-08-27 18:16 UTC by wtrocki

Sample instructions for the latest release were broken. We were telling people to execute development commands instead of running the app. What is worse is that actual development was not possible due to missing config. 

I think we need to be more solid about templates itself.

2020-08-27 18:23 UTC, wtrocki commented
Issue reported by architect.

2020-08-27 19:17 UTC, machi1990 commented on templates/ts-apollo-mongodb-backend/package.json
> +    "graphback-cli": "0.16.0-beta3",
Should this stay as was or changed or the latest release? [0.16.0-beta4](https://github.com/aerogear/graphback/releases/tag/0.16.0-beta4)?

2020-08-27 19:17 UTC, machi1990 commented on templates/ts-react-apollo-client/package.json
> +    "graphback-cli": "0.16.0-beta2",
See https://github.com/aerogear/graphback/pull/1957/files#r478640431

2020-08-27 19:19 UTC, machi1990 commented
Thanks for catching this, I've added some comments. 

> I think we need to be more solid about templates testing as this was broken for an month without anyone using/noticing.

Yes, I think the templates could use some smoke tests.

2020-08-31 09:11 UTC, wtrocki commented on templates/ts-apollo-mongodb-backend/package.json
> +    "graphback-cli": "0.16.0-beta3",
```suggestion
    "graphback-cli": "0.15.1",
```

2020-08-31 09:26 UTC, craicoverflow requested changes

2020-08-31 10:01 UTC, wtrocki commented on templates/ts-react-apollo-client/package.json
> +    "graphback-cli": "0.16.0-beta2",
```suggestion
    "graphback-cli": "0.15.1",
```

2020-08-31 10:23 UTC, machi1990 approved these changes
Comments addressed and this is good for me. 

@craicoverflow do you want to have a look? It appears to me that your comment has been addressed too.

2020-08-31 10:25 UTC, craicoverflow approved these changes

2020-08-31 10:26 UTC, merged

2020-08-31 11:51 UTC, wtrocki commented
Thx guys! Let's include this into 0.16.0 release