docs: Updated README for the ts-apollo-mongodb-datasync-backend
aerogear/graphback pull request #2112
Opened 2020-09-23 11:05 UTC by RinkiyaKeDad

Let me know what to improve :)

2020-09-23 13:14 UTC, craicoverflow commented on templates/ts-apollo-mongodb-datasync-backend/README.md
> +A template that provides you with an easy setup for your application's backend using MongoDB and Apollo server with TypeScript.
Description here mentions nothing of Data Sync capabilities of this template - would be nice to have a line showcasing this.

2020-09-23 13:15 UTC, craicoverflow requested changes
Left one comment - just need a short line mentioning data sync capability of this template. I know it is further down, but some people will not make it that far when reading.

2020-09-23 13:45 UTC, RinkiyaKeDad commented
Please check now @craicoverflow.

2020-09-24 15:55 UTC, craicoverflow approved these changes
Fantastic once again!

2020-09-24 15:55 UTC, merged