fix: unable to generate subscription query unless mutation operation in model is set to `true`
aerogear/graphback pull request #2139
Opened 2020-10-01 11:16 UTC by RinkiyaKeDad

I've updated the ```if``` conditions and it now depends only on the ```subXXX``` knobs. This should fix issue #2135. Please review the code. Thanks.

2020-10-01 14:23 UTC, machi1990 requested changes
@RinkiyaKeDad thanks you for the PR. It should be okay for `graphql` generated files. I think we should do the same for `.ts` generated files:
See
- https://github.com/aerogear/graphback/blob/e0a9f05025a06997a319aea8f8fe8ff070589cb8/packages/graphback-codegen-client/src/templates/tsTemplates.ts#L156-L191

Once that is done, can you add a snapshot test: one for `ts` and `gql`?

You can base them on 
https://github.com/aerogear/graphback/blob/e0a9f05025a06997a319aea8f8fe8ff070589cb8/packages/graphback-codegen-client/tests/GraphQLClientCreatorTest.ts#L9-L35. 

For these added tests, you can use 
```ts
 const crudMethods = {
    "create": false,
    "update": false,
    "findOne": true,
    "find": true,
    "delete": false,
    "subCreate": true,
    "subUpdate": true,
    "subDelete": true
  }
```

as a configuration.

Once that is done, we should be good to go. 

Thanks.

2020-10-03 10:51 UTC, RinkiyaKeDad commented
@machi1990 Thanks for reviewing my PR. I have never added tests before so there might be some errors. Can you please point me where I could read more about these tests and how to add them properly? Nevertheless I've tried adding them based on the ones already present. I've named the two tests and their output files arbitrarily, please tell me what would be an appropriate name for them. Thanks a lot.

2020-10-03 13:40 UTC, machi1990 commented
> @machi1990 Thanks for reviewing my PR. I have never added tests before so there might be some errors. Can you please point me where I could read more about these tests and how to add them properly? Nevertheless I've tried adding them based on the ones already present. I've named the two tests and their output files arbitrarily, please tell me what would be an appropriate name for them. Thanks a lot.

Thanks for the followup. The added tests and naming looks okay to me. This is good to go.

2020-10-03 13:41 UTC, machi1990 approved these changes

2020-10-03 13:41 UTC, merged